### ISSUE TITLE
[Bug] Serialization error

### ISSUE THREAD

**Issue by Ollix27** [mindustry-antigrief/mindustry-client#170]
### What happened?

This happpens when i join a server, then i get kicked. Newest ver of client and Garuda linux.

### Relevant log output

```shell
[E] java.io.IOException: mismatch
at mindustry.net.Net.lambda$handleException$0(Net.java:76)
at arc.util.TaskQueue.run(TaskQueue.java:17)
at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:195)
at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:57)
Caused by: arc.net.ArcNetException: Error during deserialization.
at arc.net.UdpConnection.readObject(UdpConnection.java:91)
at arc.net.Client.update(Client.java:290)
at arc.net.Client.run(Client.java:327)
at mindustry.net.ArcNetProvider.lambda$connectClient$4(ArcNetProvider.java:183)
at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: arc.net.ArcNetException: Incorrect number of bytes (20 remaining) used to deserialize object: mindustry.gen.CreateBulletCallPacket@305d0b72
at arc.net.UdpConnection.readObject(UdpConnection.java:86)
... 4 more
```

**Comment by BalaM314** [comment]
Which server? You are probably trying to join a server that has not updated to v145

**Comment by buthed010203** [comment]
Stale
